# Generated by Django 4.2.3 on 2024-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FineTunningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
