# Generated by Django 4.2.3 on 2024-08-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailbot', '0003_functions_parameters_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineTuneExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('system', models.TextField(blank=True, null=True)),
                ('assistant', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailbot.finetunningmodel')),
            ],
        ),
    ]
