# Generated by Django 4.2.3 on 2024-08-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailbot', '0004_finetuneexample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finetuneexample',
            name='model',
        ),
    ]
