# Generated by Django 4.2.3 on 2024-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbot', '0005_remove_finetuneexample_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetunningmodel',
            name='jsonl_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
