# Generated by Django 4.2.3 on 2024-08-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailbot', '0006_finetunningmodel_jsonl_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finetunningmodel',
            name='jsonl_file',
        ),
    ]
