# Generated by Django 4.2.3 on 2024-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbot', '0008_customer_product_order_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetunningmodel',
            name='output_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
